// Copyright (c) 2018 Square, Inc. All rights reserved.

#pragma once

//bit flags to indicate what features spepayment supports
typedef enum {
    CR_PAYMENT_SPE_FEATURE_QUICKCHIP_SUPPORTED              = 0x01,
    CR_PAYMENT_SPE_FEATURE_ACCOUNT_TYPE_SELECTION_SUPPORTED = 0x02,
    CR_PAYMENT_SPE_FEATURE_LEAST_COST_ROUTING_SUPPORTED     = 0x04,
    CR_PAYMENT_SPE_FEATURE_AUDIO_VISUAL_REQUEST_SUPPORTED   = 0x08,
    CR_PAYMENT_SPE_FEATURE_COMMON_DEBIT_VISA                = 0x10,
    CR_PAYMENT_SPE_FEATURE_COMMON_DEBIT_MASTERCARD          = 0x20,
    CR_PAYMENT_SPE_FEATURE_COMMON_DEBIT_DISCOVER            = 0x40,
    CR_PAYMENT_SPE_FEATURE_ENABLE_TRANSACTON_RESPONSE_V2    = 0x80,

    CR_PAYMENT_SPE_FEATURE_MULTIPLE_AUTH_REQUESTS           = 0x01,
    CR_PAYMENT_SPE_FEATURE_STORE_AND_FORWARD_MASTERCARD     = 0x02,
    CR_PAYMENT_SPE_FEATURE_STORE_AND_FORWARD_VISA           = 0x04,
    CR_PAYMENT_SPE_FEATURE_STORE_AND_FORWARD_AMEX           = 0x08,
    CR_PAYMENT_SPE_FEATURE_STORE_AND_FORWARD_DISCOVER       = 0x10,
    CR_PAYMENT_SPE_FEATURE_STORE_AND_FORWARD_JCB            = 0x20,
    CR_PAYMENT_SPE_FEATURE_STORE_AND_FORWARD_INTERAC        = 0x40,
    CR_PAYMENT_SPE_FEATURE_STORE_AND_FORWARD_EFTPOS         = 0x80,

    CR_PAYMENT_SPE_FEATURE_DISABLE_TLVDB_TAG_INDEXING       = 0x01,
    CR_PAYMENT_SPE_FEATURE_ENABLE_REMOTE_KERNELS            = 0x02,
    CR_PAYMENT_SPE_FEATURE_ENABLE_C8                        = 0x04,
    CR_PAYMENT_SPE_FEATURE_ENABLE_RECORD_V2                 = 0x08,
    CR_PAYMENT_SPE_FEATURE_ENABLE_PAYMENT_DECLINED_SOUND    = 0x10,
    CR_PAYMENT_SPE_FEATURE_COMMON_DEBIT_AMEX                = 0x20,
} cr_payment_spe_feature_t;

#define CR_PAYMENT_SPE_FEATURE_NUM_BYTES 3

typedef enum
{
    CR_PAYMENT_KERNEL_CFG_ALL_CHECK_OFF                     = 0x00,
    CR_PAYMENT_KERNEL_CFG_UGO_IAC_CHECK_ON                  = 0x01,
    CR_PAYMENT_KERNEL_CFG_ISSUER_REFERRAL_CHECK_ON          = 0x02,
    CR_PAYMENT_KERNEL_CFG_RSVD                              = 0x04, // Previously used for CR_PAYMENT_KERNEL_CFG_QUICKCHIP_SUPPORTED
    CR_PAYMENT_KERNEL_CFG_QUICKCHIP_SUPPORTED               = 0x08,
    CR_PAYMENT_KERNEL_CFG_ACCOUNT_TYPE_SELECTION_SUPPORTED  = 0x10,
} cr_payment_kernel_cfg_t;

typedef enum
{
    CR_PAYMENT_TRANSACTION_FEATURE_NONE                     = 0x00,
    CR_PAYMENT_TRANSACTION_FEATURE_QUICKCHIP                = 0x01,
    CR_PAYMENT_TRANSACTION_FEATURE_STORE_AND_FORWARD        = 0x02,
} cr_payment_transaction_feature_t;

typedef enum
{
    PAYMENT_EVENTLOG_SOURCE_0 = 0,
    PAYMENT_EVENTLOG_SOURCE_1,
} payment_eventlog_source_t;
