/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.5 */

#ifndef PB_SQUAREUP_SPE_EVENTLOG_DEFINITION_PB_H_INCLUDED
#define PB_SQUAREUP_SPE_EVENTLOG_DEFINITION_PB_H_INCLUDED
#include <LCRCore/pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 31
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _squareup_spe_EventlogDefinition {
    bool has_id;
    uint32_t id;
    bool has_name;
    char name[128];
    bool has_format;
    char format[128];
    bool has_num_params;
    uint32_t num_params;
/* @@protoc_insertion_point(struct:squareup_spe_EventlogDefinition) */
} squareup_spe_EventlogDefinition;

typedef PB_BYTES_ARRAY_T(32) squareup_spe_EventlogDefinitionCounts_event_counts_t;
typedef struct _squareup_spe_EventlogDefinitionCounts {
    bool has_event_counts;
    squareup_spe_EventlogDefinitionCounts_event_counts_t event_counts;
/* @@protoc_insertion_point(struct:squareup_spe_EventlogDefinitionCounts) */
} squareup_spe_EventlogDefinitionCounts;

/* Default values for struct fields */

/* Initializer values for message structs */
#define squareup_spe_EventlogDefinitionCounts_init_default {false, {0, {0}}}
#define squareup_spe_EventlogDefinition_init_default {false, 0, false, "", false, "", false, 0}
#define squareup_spe_EventlogDefinitionCounts_init_zero {false, {0, {0}}}
#define squareup_spe_EventlogDefinition_init_zero {false, 0, false, "", false, "", false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define squareup_spe_EventlogDefinition_id_tag   1
#define squareup_spe_EventlogDefinition_name_tag 2
#define squareup_spe_EventlogDefinition_format_tag 3
#define squareup_spe_EventlogDefinition_num_params_tag 4
#define squareup_spe_EventlogDefinitionCounts_event_counts_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_msgdesc_t squareup_spe_EventlogDefinitionCounts_fields[];
extern const pb_msgdesc_t squareup_spe_EventlogDefinition_fields[];

/* Maximum encoded size of messages (where known) */
#define squareup_spe_EventlogDefinitionCounts_size 34
#define squareup_spe_EventlogDefinition_size     274

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define EVENTLOG_DEFINITION_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
