# Uncomment the next line to define a global platform for your project
 platform :ios, '16.0'

target 'R2DistributioniOS16' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for R2DistributioniOS16
  pod 'R2Distribution', '2.2.0'


end