# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'R2DistributionSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for R2DistributionSampleApp
  pod 'R2Distribution', :git => 'git@github.com:jyotikdev/r2distributiontest.git'

end
